server:
  port: 8080
  tomcat:
    threads:
      max: 10

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.systemthinking.orderservice: DEBUG

app:
  services:
    inventory-base-url: http://localhost:8082
    payment-base-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

resilience4j:
  Circuitbreaker:
    instances:
      inventory:
        slidingWindowType: COUNT_BASED  #Resilience4j provides predefined configuration properties
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      payment:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s








